### ISSUE TITLE
Cant run example with landscapes

### ISSUE THREAD

**Issue by kkshmz** [robbiebarrat/art-DCGAN#2]
Hey,
Running this on Razerblade w/ cudnn and the CUDA installed.
Seem to be getting this error, any tips to get around it?

reads/threads.lua:183: [thread 4 callback] /home/USER/Desktop/art-DCGAN/data/donkey_folder.lua:20: bad argument #2 to 'error' (number expected, got string)

**Comment by robbiebarrat** [comment]
Please post the command you ran and the location of your "landscapes" folder

**Comment by robbiebarrat** [comment]
Hey did you ever get the issue resolved (and if so- how)? Can I close this?

**Comment by kkshmz** [comment]
DATA_ROOT=landscapes dataset=folder ndf=50 ngf=150 th main.lua

Landscapes folder is in the root folder of art-DCGAN.
I also happen to get a no display module for luarocks, though it should come with the torch installation that I think have done correctly.

**Comment by robbiebarrat** [comment]
if you're trying to use pretrained networks - instead of passing ndf=50 and ngf=150, you need to pass
`netD=path_to_discriminator_net.t7`
`netG=path_to_generator_net.t7`

Also, your landscapes folder is titled "landscapes" and not "landscape"? Make sure the folder name is correct, because the error you're getting is related to loading the data.

**Comment by kkshmz** [comment]
Hey, thanks for the advice. I decided to full path everything, but I get this error, landscapes file is created with the default scraping.

/home/rzmml/torch/install/bin/luajit: /home/rzmml/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 2 callback] /home/rzmml/torch/install/share/lua/5.1/image/init.lua:235: Not a JPEG file: starts with 0x47 0x49

**Comment by robbiebarrat** [comment]
Hm... Looks like the scraper couldn't finish downloading a few of the images...

If you're on linux, you can run `find . -iname '*.jpg' -print0 | xargs -0 jpeginfo -c` and delete all of the files it says there, but if you're on windows you'll have to just sort the images by file size and delete the ~10 smallest and ~10 largest images... The scraper usually messes up on those. 

I'll commit something hopefully this weekend and add that into the scraper, but for now you'll have to do it manually :(
