### ISSUE TITLE
Error with own image dataset

### ISSUE THREAD

**Issue by j3nsykes** [robbiebarrat/art-DCGAN#7]
Despite installing dependancies I'm getting this error when trying to train my own very small dataset. Could it be the naming or formatting of the jpg? They are named 001.jpg etc and have RGB no alpha channel colour properties. 
Any help would be appreciated. 

> Random Seed: 2589	
> Starting donkey with id: 3 seed: 2592
> table: 0x418eb430
> Starting donkey with id: 4 seed: 2593
> table: 0x40715898
> Starting donkey with id: 2 seed: 2591
> table: 0x41bebf68
> Starting donkey with id: 1 seed: 2590
> table: 0x4190c650
> Loading train metadata from cache
> Loading train metadata from cache
> Loading train metadata from cache
> Loading train metadata from cache
> Dataset: folder	 Size: 	455	
> /home/paperspace/torch/install/bin/luajit: ...perspace/torch/install/share/lua/5.1/threads/threads.lua:315: ...perspace/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 3 callback] /home/paperspace/torch/install/share/lua/5.1/image/init.lua:235: Not a JPEG file: starts with 0x00 0x00
> stack traceback:
> 	[C]: in function 'load'
> 	/home/paperspace/torch/install/share/lua/5.1/image/init.lua:235: in function 'loader'
> 	/home/paperspace/torch/install/share/lua/5.1/image/init.lua:388: in function 'load'
> 	/home/paperspace/art-DCGAN/data/donkey_folder.lua:34: in function 'loadImage'
> 	/home/paperspace/art-DCGAN/data/donkey_folder.lua:54: in function 'getByClass'
> 	/home/paperspace/art-DCGAN/data/dataset.lua:341: in function </home/paperspace/art-DCGAN/data/dataset.lua:335>
> 	[C]: in function 'xpcall'
> 	...perspace/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
> 	...paperspace/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...paperspace/torch/install/share/lua/5.1/threads/queue.lua:41>
> 	[C]: in function 'pcall'
> 	...paperspace/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
> 	[string "  local Queue = require 'threads.queue'..."]:15: in main chunk
>

**Comment by robbiebarrat** [comment]
That's really strange... Try to uninstall torch completely and do a reinstall; sometimes stuff like this happens if you already have an incomplete torch install and then try to install it again.

**Comment by j3nsykes** [comment]
Yep that was it thanks
