### ISSUE TITLE
can't seem to scrape wikiart!

### ISSUE THREAD

**Issue by talvasconcelos** [robbiebarrat/art-DCGAN#8]
Maybe the website as changed, but i can't seem to get the scraper getting the images.

**Comment by jclancy93** [comment]
I was having the same issue. I took a look at the Python script and it looks like the markup has totally changed. WikiArt is now a SPA which makes scraping very tricky. 

I wrote some javascript in the browser console on WikiArt that saved all the image urls into a file and then altered the python script to download from a list of urls..

@robbiebarrat probably worth noting that the scraper doesn't work anymore though. What could work is just having a folder of .txt files that just contained all the URLs for images in each of the genres and changing the python script to just download a certain genre or art based on an argument. 

I'd be happy to submit a PR if this was something you were interested in 👍

**Comment by talvasconcelos** [comment]
Hi, thanks for the reply. Yes the website is an angular SPA. The scrapper fails to "mount" the website before trying to looking for the images.

I found that kaggle has the dataset available for download: https://www.kaggle.com/c/painter-by-numbers/data

**Comment by robbiebarrat** [comment]
closing this issue now since the scraper is updated + working now.
